# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_auto_20160430_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='from_email',
            field=models.EmailField(max_length=254),
        ),
    ]
